### ISSUE TITLE
can this thing generate bigger than 256 pixel result?

### ISSUE THREAD

**Issue by FurkanGozukara** [hamadichihaoui/BIRD#4]
I just tested super resolution yes it works but can it generate bigger than 256 or always 256?

how to generate bigger than 256?

and you call 256px super resolution? :D

also here my test results i think you really should write some proper instructions this is a shame

input image to test

![00105-3475094938](https://github.com/hamadichihaoui/BIRD/assets/19240467/cf730361-6d4a-4116-929a-c9b6c6b25003)

and here the output of [super_resolution.py](https://github.com/hamadichihaoui/BIRD/blob/master/super_resolution.py)

![super_resolution](https://github.com/hamadichihaoui/BIRD/assets/19240467/27830486-bdbc-4751-b76f-6b10b75e0a7b)

so it generated this simply

![img_1717961388578](https://github.com/hamadichihaoui/BIRD/assets/19240467/31cd110d-1dbc-4d68-855d-418f118604e8)

**Comment by Dazzaxa9691** [comment]
Hmm the results look good but  256px interested to see if this cab be improved

**Comment by hamadichihaoui** [comment]
@FurkanGozukara  Thanks for your interest in our work!
Our method can work with any resolution as long as i) you have enough memory because inference at high resolution needs more memory ii) the pre-trained diffusion model is trained using the same type of data and  (approximately) the same resolution so there will be no domain gap.
Now, why the result that you get for the example you should is not good? The answer is simply the domain gap. The pre-trained model that we use was trained only curated and centered faces (using FFHQ dataset if I am not wrong and did not see during training a person with a part of the body like the one you use in this example).

**Comment by FurkanGozukara** [comment]
@hamadichihaoui so we have to train ourselves to make it useful? Nothing good pretrained by you right? Like SUPIR

For example SUPIR is able to upscale literally anything with the very best results right now. Even better than commercial apps like Topaz AI

**Comment by Katehuuh** [comment]
> @hamadichihaoui so we have to train ourselves to make it useful? Nothing good pretrained by you right? Like SUPIR

`Centered faces` only as shown in examples.:
![super_resolution](https://github.com/hamadichihaoui/BIRD/assets/133996730/6eea2fcb-da39-4d08-9e21-0a6e63e4a3c2)

> i think you really should write some proper instructions this is a shame

More likely, combine in one `blind_deblurring`, `blind_non_uniform_deblurring`, `inpainting`, `super_resolution` with arg for path instead of [example path **already processed**](https://github.com/hamadichihaoui/BIRD/blob/master/data/imgs/00201.png)., (and maybe ensure convert img to 24bit to handle 32bit error.)

---
> @FurkanGozukara ... you have enough memory because inference at high resolution needs more memory

high resolution not possible to modify as in config:
https://github.com/hamadichihaoui/BIRD/blob/03dff34b46703eba678bb4d30e06927220b6b806/data/celeba_hq.yml#L4

**Comment by FurkanGozukara** [comment]
i see looks like another repo i spent time for nothing :D

meanwhile these are from SUPIR just upscaled to use in my newest tutorial

it is a chinese model by the way public open source 

![3 comparison](https://github.com/hamadichihaoui/BIRD/assets/19240467/5818c2e2-c443-46b5-bebc-6fc7fa5ec3fa)

![upscale](https://github.com/hamadichihaoui/BIRD/assets/19240467/f915b6fc-6bea-4ee8-8ab2-ae6fea7e339c)

![2cc37a29c165655d07a5aaeb91699b16d25680ab (1)](https://github.com/hamadichihaoui/BIRD/assets/19240467/680bb935-342b-4d9b-a49e-66953750f740)

![canva](https://github.com/hamadichihaoui/BIRD/assets/19240467/7a97e3a0-7c1d-444c-a89f-6288c60b622b)

![config](https://github.com/hamadichihaoui/BIRD/assets/19240467/4fd166df-2c00-4353-8fbd-14436694a881)

![Copy of v-express (1)](https://github.com/hamadichihaoui/BIRD/assets/19240467/91c9ad2f-1bdf-4bc5-ac52-2aaa16eb9ace)

**Comment by hamadichihaoui** [comment]
@FurkanGozukara  I think you are missing something here. SIPIR was trained with more than 20 millions images with text annotations. It is specialized in superresolution. The model that we use here for faces is trained using 60K images (without text annotations) and we can handle different restoration tasks (superresolution, inpainting..). Here we just present an idea and a proof of concept. At the end, the comparison with SIPIR is unfair.
I know that you probably don't care about all of this but just wanted to point it out.

**Comment by FurkanGozukara** [comment]
@hamadichihaoui ty for replies
